apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pg
  template:
    metadata:
      labels:
        app: pg
    spec:
      containers:
        - name: pg
          image: postgres
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: 'rainforest'
---
apiVersion: v1
kind: Service
metadata:
  name: pg-serv
spec:
  selector:
    app: pg
  ports:
    - name: pg
      protocol: TCP
      port: 5432
      targetPort: 5432
  