module.exports = {
    //ErrorTypes
    INVALID_INPUT: 'INVALID_INPUT',
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    REQUIRED_DATA_MISSING: 'REQUIRED_DATA_MISSING',

    //Error fields
    GLOBAL: 'GLOBAL',
    EMAIL: 'EMAIL',

    /*
    * Error message keys
    */
    //Validation Errors
    NULL_OR_EMPTY: 'NULL_OR_EMPTY',
    NOT_ALPHABETIC: 'NOT_ALPHABETIC',
    NOT_REQ_LENGTH: 'NOT_REQ_LENGTH',
    MIN_REQ_LENGTH: 'MIN_REQ_LENGTH|',
    NOT_EMAIL: 'NOT_EMAIL',
    NOT_URL: 'NOT_URL',
    NOT_NUMERIC: 'NOT_NUMERIC',
    NOT_IN_LIST: 'NOT_IN_LIST',
    NOT_UNIQUE: 'ALREADY_EXISTS',

    //User Errors
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    PASSWORD_NO_MATCH: 'PASSWORD_NO_MATCH',
    EMAIL_CANNOT_UPDATE: 'EMAIL_CANNOT_UPDATE',
    DATA_NOT_FOUND: 'DATA_NOT_FOUND',
    CART_EMPTY: 'CART_EMPTY',

}