apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: rahulramesha/rainforest-api
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: '3000'
            - name: REDIS_PORT
              value: '6379'
            - name: REDIS_HOST
              value: redis-serv
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: apisecret
                  key: JWT_SECRET_KEY
            #- name: TLS_CERT
            #  valueFrom:
            #    secretKeyRef:
            #      name: tlssecret
            #      key: tls.crt
            #- name: TLS_KEY
            #  valueFrom:
            #    secretKeyRef:
            #      name: tlssecret
            #      key: tls.key
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_PASSWORD
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: NODE_ENV
            - name: POSTGRES_DB
              value: 'rainforest'
---
apiVersion: v1
kind: Service
metadata:
  name: api-serv
spec:
  selector:
    app: api
  ports:
    - name: api
      protocol: TCP
      port: 3000
      targetPort: 3000